# Generated by Django 4.2.4 on 2023-08-18 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(max_length=150)),
                ('blogPost', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('date_published', models.DateTimeField(default=datetime.datetime(2023, 8, 18, 9, 48, 55, 105860, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
