# Generated by Django 4.2.4 on 2023-08-24 06:35

import blogapp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blog_blogimage_alter_blog_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogUserImage',
            field=models.ImageField(default='blogs/avatar.png', upload_to=blogapp.models.upload_to, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogImage',
            field=models.ImageField(default='blogs/default.png', upload_to=blogapp.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 35, 3, 770538, tzinfo=datetime.timezone.utc)),
        ),
    ]
