# Generated by Django 4.2.4 on 2023-08-29 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_blog_bloguserimage_alter_blog_blogimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 5, 30, 41, 159019, tzinfo=datetime.timezone.utc)),
        ),
    ]
